name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: |
        npm install
    - name: build docker image
      run: docker build -t basic-node-app .
    - name: push to package registry
      uses: mattdavis0351/actions/docker-gpr@v1
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: basic-node-app
